import streamlit as st
import google.generativeai as palm
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.environ.get("PALM_API_KEY")
palm.configure(api_key=API_KEY)

def main():
    st.header("Film Review ")
    st.write("Get a comprehensive movie review generated by AI, along with a captivating poster!")

    movie_title = st.text_input("Enter the title of the movie you want to review:")

    if st.button("Generate Review", use_container_width=True):
        model = "models/text-bison-001"  # Replace with a suitable text-generation model

        prompt = f"Generate a detailed and informative review of the movie {movie_title}, covering its plot, characters, themes, cinematography, and overall impact. Include a relevant and visually appealing poster image."

        response = palm.generate_text(
            model=model,
            prompt=prompt,
            max_output_tokens=1500  # Adjust as needed
        )

        try:
            review_text, poster_url = response.result.split("||")  # Split text and image URL
            st.image(poster_url, width=400)
            st.write("**Review:**")
            st.markdown(review_text, unsafe_allow_html=True)
        except ValueError:
            st.error("Failed to retrieve poster image. Here's the text-only review:")
            st.markdown(response.result, unsafe_allow_html=True)

if __name__ == "__main__":
    main()
